# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.md')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    long_description_content_type='text/markdown',
    name='runrestic',
    version='0.3.6',
    description='A wrapper script for Restic backup software that inits, creates, prunes and checks backups',
    python_requires='==3.*,>=3.4.0',
    project_urls={
        'homepage': 'https://github.com/andreasnuesslein/runrestic',
        'repository': 'https://github.com/andreasnuesslein/runrestic'
    },
    author='Andreas Nüßlein',
    author_email='andreas@nuessle.in',
    license='GPL-3.0+',
    keywords='backup',
    classifiers=[
        'Development Status :: 4 - Beta', 'Environment :: Console',
        'Intended Audience :: System Administrators',
        'Programming Language :: Python', 'Topic :: Security :: Cryptography',
        'Topic :: System :: Archiving :: Backup'
    ],
    entry_points={
        'console_scripts': ['runrestic = runrestic.commands.runrestic:main']
    },
    packages=[
        'runrestic', 'runrestic.commands', 'runrestic.config',
        'runrestic.metrics', 'runrestic.restic', 'runrestic.runrestic',
        'runrestic.tools'
    ],
    package_data={'runrestic.config': ['*.json']},
    install_requires=['jsonschema==3.0.*,>=3.0.0', 'toml==0.10.*,>=0.10.0'],
    extras_require={'dev': ['ipdb']},
)
